# Generated by Django 4.0.5 on 2023-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(choices=[('1', 'Particular'), ('2', 'Transporte'), ('3', 'Carga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[('1', 'Ford'), ('2', 'Chevrolet'), ('3', 'Fiat'), ('4', 'Toyota')], max_length=20),
        ),
    ]
